# Site settings
title: cregox
email: help@cregox.net
description: do worry, plus be happy # default, also for opengraph
image: /cregox_ana_boat_thumb.jpg # doesn't work for anything, expected og
baseurl: "" # site's subpath, e.g. /blog/
url: https://cregox.net # the base hostname & protocol for your site
github_url: https://github.com/cregox/cregox.github.io
twitter_username: cauerego
github_username: cauerego
google_analytics: UA-4687862-8 # placed on head include
include: [".well-known"]

# (hopefuly) widely used external links
a:
  caue:
    casting: https://b.cregox.net/caue-casting
    github: https://github.com/cauerego
    abaixatampa: http://bit.ly/abaixatampa
  skills: https://b.cregox.net/skills
  youtube: https://www.youtube.com/c/cauerego
  instagram: https://www.instagram.com/cregox/
  eta: http://www.estudiodetreinamento.com.br/
  abaixatampa: http://abaixatampa.wordpress.com/
  damme: http://youtu.be/fxMaeJjY4jk
  stackoverflow: http://stackoverflow.com/story/cauerego
  unity3d: http://answers.unity3d.com/users/822/cawas.html

defaults:
  -
    scope:
      path: "talk"
      type: pages
    values:
      layout: talk # overrides previous default layout
      google_analytics: # placed on files by httrack and talk layout


# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
