# Site settings
title: cregox
email: help@cregox.net
description: do worry, plus be happy # default, also for opengraph
image: /cregox_ana_boat_thumb.jpg # doesn't work for anything, expected og
baseurl: "" # site's subpath, e.g. /blog/
url: https://cregox.net # the base hostname & protocol for your site
github_url: https://github.com/cregox/cregox.github.io
twitter_username: cauerego
github_username: cauerego
include: [".well-known"]

# tracking is a waste of resources. profit from sharing and caring instead #lifeprofit cregox.net/tracking 
#google_analytics: UA-4687862-8 # placed on head include

# (hopefuly) widely used external links
duck: "&kp=-2&k1=-1&kj=g2&kam=osm"
a:
  caue:
    casting: https://b.cregox.net/caue-casting
    github: https://github.com/cauerego
    abaixatampa: http://bit.ly/abaixatampa
  skills: https://b.cregox.net/skills
  youtube: https://www.youtube.com/c/cauerego
  instagram: https://www.instagram.com/cregox/
  eta: http://www.estudiodetreinamento.com.br/
  abaixatampa: http://abaixatampa.wordpress.com/
  damme: http://youtu.be/fxMaeJjY4jk
  stackoverflow: http://stackoverflow.com/story/cauerego
  unity3d: http://answers.unity3d.com/users/822/cawas.html

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
gallery_dir: "gallery"
# Any valid value of "background-position" CSS attribute.
image_position: "left center"

defaults:
 - scope:
    path: "" # an empty string here means all files in the project
   values:
    layout: default
 - scope:
    path: "talk"
    type: pages
   values:
    layout: talk # overrides previous default layout
    google_analytics: # placed on files by httrack and talk layout
 - scope:
     # Should be same as the `gallery_dir` key above.
    path: "gallery"
   values:
    image: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
