# Site settings
title: cregox (caue rego)
email: b@cregox.net
description: get to know us a bit more
baseurl: "" # site's subpath, e.g. /blog/
url: https://cregox.net # the base hostname & protocol for your site
github_url: https://github.com/cregox/cregox.github.io
twitter_username: cauerego
github_username: cauerego
google_analytics: UA-4687862-8 # placed on head include

defaults:
  -
    scope:
      path: "talk"
      type: pages
    values:
      layout: talk # overrides previous default layout
      google_analytics: # placed on files by httrack and talk layout


# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
