# Site settings
title: cregox
email: help@cregox.net
description: do worry, plus be happy # default, also for opengraph
image: /cregox_ana_boat_thumb.jpg # doesn't work for anything, expected og
baseurl: "" # site's subpath, e.g. /blog/
url: https://cregox.net # the base hostname & protocol for your site
github_url: https://github.com/cregox/cregox.github.io
twitter_username: cauerego
github_username: cauerego
google_analytics: UA-4687862-8 # placed on head include

# widely used external links
a:
  caue:
    casting: https://b.cregox.net/caue-casting
  skills: https://b.cregox.net/skills
  youtube: https://www.youtube.com/c/cauerego
  instagram: https://www.instagram.com/cregox/
  eta: http://www.estudiodetreinamento.com.br/
  abaixatampa: http://abaixatampa.wordpress.com/
  damme: http://youtu.be/fxMaeJjY4jk
  cregox:
    wiki:
      game: https://en.wikipedia.org/wiki/User:Cregox/-%3F_wiki%3F
      old:
        user: https://en.wikipedia.org/w/index.php?title=User:Cregox&oldid=220362058
    quora:
      sandra: https://www.quora.com/What-kind-of-hobbies-do-highly-intelligent-i-e-those-with-intelligence-levels-beyond-the-exceptional-people-have/answer/Caue-Rego?srid=ptsW
    github:
      wiki:
        novel: https://github.com/cauerego/cauerego.github.io/wiki/a-novel-about-the-other-novel

defaults:
  -
    scope:
      path: "talk"
      type: pages
    values:
      layout: talk # overrides previous default layout
      google_analytics: # placed on files by httrack and talk layout


# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
